name: Deploy AWS AppSync Project

on:
  workflow_dispatch:
    inputs:
      aws_region:
        description: Target AWS Region
        default: "us-east-1"
        type: string
      backend_s3_bucket:
        description: Name of the S3 bucket for Terraform backend
        default: "2024-terraform-backend"
        type: string
      backend_dynamodb_table:
        description: DynamoDB table for State lock
        default: "terraform-backend-ddb"
        type: string
      aws_account_id:
        description: AWS Account ID
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ inputs.aws_account_id }}:role/github-actions-dsl
          aws-region: ${{ inputs.aws_region }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false          

      - name: Terraform Init
        shell: bash
        run: |
          set -eux
          terraform init -upgrade -reconfigure \
            -backend-config='region=${{ inputs.aws_region }}' \
            -backend-config='bucket=${{ inputs.backend_s3_bucket }}' \
            -backend-config='key=appsync-project/terraform.tfstate' \
            -backend-config='dynamodb_table=${{ inputs.backend_dynamodb_table }}'
        working-directory: .terraform

      - name: Terraform Apply
        shell: bash
        run: |
          set -eux
          terraform apply -auto-approve
        working-directory: .terraform
